import type { Metadata } from "next";
import { Geist_Mono, Lora, Nunito } from "next/font/google";
import "./globals.css";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Body text: keep weights minimal (adjust as needed)
const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
  weight: ["400","600"],        // keep lean
  display: "swap",
  preload: true,
  adjustFontFallback: true,
  fallback: ["system-ui","Segoe UI","Roboto","Helvetica","Arial"],
});

// Headers: preload only the weights/styles you use (e.g., 700, 400 italic)
const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  weight: ["700","600","500","400"], // supported Lora weights; use 700 for headings
  style: ["normal"],              // keep minimal; add italic only if used
  display: "swap",
  preload: true,                // ensures early fetch
  adjustFontFallback: true,
  fallback: ["Georgia","Times New Roman","Times","serif"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} ${lora.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
